package com.walker.kapt.compiler


/**
 * Created by lizhiping on 2022/12/13.
 * <p>
 * description
 */
object Constant {
    // 对应app模块中类所在的包名
    const val PACKAGE_NAME = "com.demo.kapt"

    const val CODE_COMMENT = "generated by IDE, do not edit it."
}