package com.walker.kapt.compiler


/**
 * Created by lizhiping on 2022/12/13.
 * <p>
 * description
 */
object Constant {
    const val PACKAGE_NAME = "com.walker.kapt"

    const val CODE_COMMENT = "generated by IDE, do not edit it."
}