package com.demo.storage;

import androidx.annotation.NonNull;
import com.walker.storage.winkkv.WinkKV;
import io.packable.PackDecoder;
import io.packable.PackEncoder;

/**
 * This class is generated by IDE, do not edit.
 */
public class PackableObject$Encoder implements WinkKV.Encoder<PackableObject> {

    public static PackableObject$Encoder INSTANCE = new PackableObject$Encoder();

    private PackableObject$Encoder() {
    }

    @Override
    public String tag() {
        return "PackableObject$Encoder";
    }

    @Override
    public byte[] encode(@NonNull PackableObject obj) {
        return PackEncoder.marshal(obj);
    }

    @Override
    public PackableObject decode(@NonNull byte[] bytes, int offset, int length) {
        return PackDecoder.unmarshal(bytes, offset, length, PackableObject.CREATOR);
    }

}
